name: on_audio_room
description: Flutter Package used to create a room to storage audio sections [Favorites, Internal Playlists, Most Played, etc...].
version: 2.2.1+1
homepage: https://github.com/LucJosin/on_audio_room
# pub.dev: https://pub.dev/packages/on_audio_room
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Database
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # UUID Generator
  nanoid: ^1.0.0

  # FLutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Database
  hive_generator: ^1.1.0

  # Code Generator
  build_runner: ^2.0.6

  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:



